app_product_test_:
    resource: "@AppBundle/Controller/ProductRESTController.php"
    type:   rest
    prefix:   /test/

app_post_product:
    resource: "@AppBundle/Controller/PostRESTController.php"
    type:   rest
    prefix:   /product

app:
    resource: '@AppBundle/Controller/'
    type: annotation
